from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

from app.config import settings

engine = create_engine(
    settings.database_url, connect_args={"check_same_thread": False}, echo=True
)
'''
connect_args={"check_same_thread": False} is used for SQLite databases to allow the same connection to be used across different threads. This is necessary because SQLite has limitations with multi-threaded access. The echo=True parameter enables logging of all SQL statements generated by SQLAlchemy, which can be useful for debugging and monitoring database interactions. Samjha mamu!!
'''
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()
