from sqlalchemy import create_engine, event
from sqlalchemy.orm import declarative_base, sessionmaker

from app.config import settings

SQLITE_BUSY_TIMEOUT_MS = 5000


def create_sqlite_engine(database_url: str, echo: bool = True):
    """SQLite engine whose transactions take the write lock up front.

    Rate limiting reads a client's bucket, computes a new level, and writes it
    back. Under SQLAlchemy's default deferred BEGIN, concurrent requests all
    read the same pre-debit level, all pass the check, and then overwrite each
    other's debits — verified: 8 concurrent requests all passed a bucket with
    capacity for 1. BEGIN IMMEDIATE serializes those transactions so the
    read-modify-write is atomic across both threads and processes.
    """
    engine = create_engine(
        database_url,
        # isolation_level=None hands transaction control to SQLAlchemy, so the
        # explicit BEGIN IMMEDIATE below isn't rejected as a nested BEGIN.
        connect_args={"check_same_thread": False, "isolation_level": None},
        echo=echo,
    )

    @event.listens_for(engine, "connect")
    def _set_busy_timeout(dbapi_connection, _connection_record):
        # Without this, a blocked writer errors immediately instead of waiting.
        dbapi_connection.execute(f"PRAGMA busy_timeout = {SQLITE_BUSY_TIMEOUT_MS}")

    @event.listens_for(engine, "begin")
    def _begin_immediate(connection):
        connection.exec_driver_sql("BEGIN IMMEDIATE")

    return engine


engine = create_sqlite_engine(settings.database_url)
'''
connect_args={"check_same_thread": False} is used for SQLite databases to allow the same connection to be used across different threads. This is necessary because SQLite has limitations with multi-threaded access. The echo=True parameter enables logging of all SQL statements generated by SQLAlchemy, which can be useful for debugging and monitoring database interactions. Samjha mamu!!
'''
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()
